### ISSUE TITLE
Support glob and/or folder names with `--recursive`

### ISSUE THREAD

**Issue by Turbo87** [auth0/mocha-only-detector#3]
It would be awesome if this project would support calling it like this:

```
mocha-only-detector "tests/**/*.js"
```

or this:

```
mocha-only-detector tests --recursive
```

**Comment by pose** [comment]
@Turbo87 have you checked [this](https://github.com/pose/mocha-only-detector/blob/master/package.json#L34)? You should be able to do:

``` sh
mocha-only-detector-glob "tests/**/*.js"
```

Let me know if that does not work for you.

Thanks in advance,

**Comment by Turbo87** [comment]
didn't know about that. What's the reason for making that a separate executable?

**Comment by pose** [comment]
No reason, just lack of time :). Feel free to create a PR if you want to unify both scripts into one. Thanks!
